In [43]:
from sklearn import datasets
import pandas as pd

In [44]:
iris = datasets.load_iris()

In [45]:
def abc(k, *val):
    if k < val[0]:
        return 0
    else:
        return 1

In [46]:
def label(val, *boundaries):
    if (val < boundaries[0]):
        return 'a'
    elif (val < boundaries[1]):
        return 'b'
    elif (val < boundaries[2]):
        return 'c'
    else:
        return 'd'

def toLabel(df, old_feature_name):
    second = df[old_feature_name].mean()
    minimum = df[old_feature_name].min()
    first = (minimum + second)/2
    maximum = df[old_feature_name].max()
    third = (maximum + second)/2
    return df[old_feature_name].apply(label, args= (first, second, third))

In [47]:
def makeClassData(iris):
    df = pd.DataFrame(iris.data)
    df.columns = ["sl", "sw", 'pl', 'pw']
    df.sl.apply(abc, args=(5,))
    df['sl_labeled'] = toLabel(df, 'sl')
    df['sw_labeled'] = toLabel(df, 'sw')
    df['pl_labeled'] = toLabel(df, 'pl')
    df['pw_labeled'] = toLabel(df, 'pw')
    df.drop(['sl', 'sw', 'pl', 'pw'], axis = 1, inplace = True)
    df["output"] = iris.target
    return df

In [48]:
def fit(data):
    output_name = data.columns[-1]
    features = data.columns[0:-1]
    counts = {}
    possible_outputs = set(data[output_name])
    for output in possible_outputs:
        counts[output] = {}
        smallData = data[data[output_name] == output]
        counts[output]["total_count"] = len(smallData)
        for f in features:
            counts[output][f] = {}
            possible_values = set(smallData[f])
            for value in possible_values:
                val_count = len(smallData[smallData[f] == value])
                counts[output][f][value] = val_count
    return counts

In [114]:
df = makeClassData(iris)
counts = fit(df)
pi = cal_pi(counts)
columns = list(df.columns)

In [50]:
def cal_pi(counts):
    sum = 0
    for i in counts:
        sum += counts[i]['total_count']
    p = {}
    for i in counts:
        p[i] = counts[i]['total_count'] / sum
    return p

In [115]:
counts, pi

({0: {'total_count': 50,
   'sl_labeled': {'a': 28, 'b': 22},
   'sw_labeled': {'b': 7, 'a': 1, 'd': 10, 'c': 32},
   'pl_labeled': {'a': 50},
   'pw_labeled': {'a': 50}},
  1: {'total_count': 50,
   'sl_labeled': {'b': 21, 'a': 3, 'd': 2, 'c': 24},
   'sw_labeled': {'b': 29, 'a': 13, 'c': 8},
   'pl_labeled': {'b': 7, 'c': 43},
   'pw_labeled': {'b': 10, 'c': 40}},
  2: {'total_count': 50,
   'sl_labeled': {'b': 5, 'a': 1, 'd': 15, 'c': 29},
   'sw_labeled': {'b': 28, 'a': 5, 'd': 2, 'c': 15},
   'pl_labeled': {'d': 30, 'c': 20},
   'pw_labeled': {'d': 34, 'c': 16}}},
 {0: 0.3333333333333333, 1: 0.3333333333333333, 2: 0.3333333333333333})

In [110]:
predict(df, counts)

sl_labeled    b
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 0, dtype: object
sl_labeled    b
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 0, dtype: object
sl_labeled    b
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 0, dtype: object
sl_labeled    a
sw_labeled    b
pl_labeled    a
pw_labeled    a
output        0
Name: 1, dtype: object
sl_labeled    a
sw_labeled    b
pl_labeled    a
pw_labeled    a
output        0
Name: 1, dtype: object
sl_labeled    a
sw_labeled    b
pl_labeled    a
pw_labeled    a
output        0
Name: 1, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 2, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 2, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 2, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 3, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 3, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 3, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 4, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 4, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 4, dtype: object
sl_labeled    b
sw_labeled    d
pl_labeled    a
pw_labeled    a
output        0
Name: 5, dtype: object
sl_labeled    b
sw_labeled    d
pl_labeled    a
pw_labeled    a
output        0
Name: 5, dtype: object
sl_labeled    b
sw_labeled    d
pl_labeled    a
pw_labeled    a
output        0
Name: 5, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 6, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 6, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 6, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 7, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 7, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 7, dtype: object
sl_labeled    a
sw_labeled    b
pl_labeled    a
pw_labeled    a
output        0
Name: 8, dtype: object
sl_labeled    a
sw_labeled    b
pl_labeled    a
pw_labeled    a
output        0
Name: 8, dtype: object
sl_labeled    a
sw_labeled    b
pl_labeled    a
pw_labeled    a
output        0
Name: 8, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 9, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 9, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 9, dtype: object
sl_labeled    b
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 10, dtype: object
sl_labeled    b
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 10, dtype: object
sl_labeled    b
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 10, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 11, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 11, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 11, dtype: object
sl_labeled    a
sw_labeled    b
pl_labeled    a
pw_labeled    a
output        0
Name: 12, dtype: object
sl_labeled    a
sw_labeled    b
pl_labeled    a
pw_labeled    a
output        0
Name: 12, dtype: object
sl_labeled    a
sw_labeled    b
pl_labeled    a
pw_labeled    a
output        0
Name: 12, dtype: object
sl_labeled    a
sw_labeled    b
pl_labeled    a
pw_labeled    a
output        0
Name: 13, dtype: object
sl_labeled    a
sw_labeled    b
pl_labeled    a
pw_labeled    a
output        0
Name: 13, dtype: object
sl_labeled    a
sw_labeled    b
pl_labeled    a
pw_labeled    a
output        0
Name: 13, dtype: object
sl_labeled    b
sw_labeled    d
pl_labeled    a
pw_labeled    a
output        0
Name: 14, dtype: object
sl_labeled    b
sw_labeled    d
pl_labeled    a
pw_labeled    a
output        0
Name: 14, dtype: object
sl_labeled    b
sw_labeled    d
pl_labeled    a
pw_labeled    a
output        0
Name: 14, dtype: object
sl_labeled    b
sw_labeled    d
pl_labeled    a
pw_labeled    a
output        0
Name: 15, dtype: object
sl_labeled    b
sw_labeled    d
pl_labeled    a
pw_labeled    a
output        0
Name: 15, dtype: object
sl_labeled    b
sw_labeled    d
pl_labeled    a
pw_labeled    a
output        0
Name: 15, dtype: object
sl_labeled    b
sw_labeled    d
pl_labeled    a
pw_labeled    a
output        0
Name: 16, dtype: object
sl_labeled    b
sw_labeled    d
pl_labeled    a
pw_labeled    a
output        0
Name: 16, dtype: object
sl_labeled    b
sw_labeled    d
pl_labeled    a
pw_labeled    a
output        0
Name: 16, dtype: object
sl_labeled    b
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 17, dtype: object
sl_labeled    b
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 17, dtype: object
sl_labeled    b
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 17, dtype: object
sl_labeled    b
sw_labeled    d
pl_labeled    a
pw_labeled    a
output        0
Name: 18, dtype: object
sl_labeled    b
sw_labeled    d
pl_labeled    a
pw_labeled    a
output        0
Name: 18, dtype: object
sl_labeled    b
sw_labeled    d
pl_labeled    a
pw_labeled    a
output        0
Name: 18, dtype: object
sl_labeled    b
sw_labeled    d
pl_labeled    a
pw_labeled    a
output        0
Name: 19, dtype: object
sl_labeled    b
sw_labeled    d
pl_labeled    a
pw_labeled    a
output        0
Name: 19, dtype: object
sl_labeled    b
sw_labeled    d
pl_labeled    a
pw_labeled    a
output        0
Name: 19, dtype: object
sl_labeled    b
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 20, dtype: object
sl_labeled    b
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 20, dtype: object
sl_labeled    b
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 20, dtype: object
sl_labeled    b
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 21, dtype: object
sl_labeled    b
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 21, dtype: object
sl_labeled    b
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 21, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 22, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 22, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 22, dtype: object
sl_labeled    b
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 23, dtype: object
sl_labeled    b
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 23, dtype: object
sl_labeled    b
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 23, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 24, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 24, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 24, dtype: object
sl_labeled    a
sw_labeled    b
pl_labeled    a
pw_labeled    a
output        0
Name: 25, dtype: object
sl_labeled    a
sw_labeled    b
pl_labeled    a
pw_labeled    a
output        0
Name: 25, dtype: object
sl_labeled    a
sw_labeled    b
pl_labeled    a
pw_labeled    a
output        0
Name: 25, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 26, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 26, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 26, dtype: object
sl_labeled    b
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 27, dtype: object
sl_labeled    b
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 27, dtype: object
sl_labeled    b
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 27, dtype: object
sl_labeled    b
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 28, dtype: object
sl_labeled    b
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 28, dtype: object
sl_labeled    b
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 28, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 29, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 29, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 29, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 30, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 30, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 30, dtype: object
sl_labeled    b
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 31, dtype: object
sl_labeled    b
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 31, dtype: object
sl_labeled    b
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 31, dtype: object
sl_labeled    b
sw_labeled    d
pl_labeled    a
pw_labeled    a
output        0
Name: 32, dtype: object
sl_labeled    b
sw_labeled    d
pl_labeled    a
pw_labeled    a
output        0
Name: 32, dtype: object
sl_labeled    b
sw_labeled    d
pl_labeled    a
pw_labeled    a
output        0
Name: 32, dtype: object
sl_labeled    b
sw_labeled    d
pl_labeled    a
pw_labeled    a
output        0
Name: 33, dtype: object
sl_labeled    b
sw_labeled    d
pl_labeled    a
pw_labeled    a
output        0
Name: 33, dtype: object
sl_labeled    b
sw_labeled    d
pl_labeled    a
pw_labeled    a
output        0
Name: 33, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 34, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 34, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 34, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 35, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 35, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 35, dtype: object
sl_labeled    b
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 36, dtype: object
sl_labeled    b
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 36, dtype: object
sl_labeled    b
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 36, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 37, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 37, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 37, dtype: object
sl_labeled    a
sw_labeled    b
pl_labeled    a
pw_labeled    a
output        0
Name: 38, dtype: object
sl_labeled    a
sw_labeled    b
pl_labeled    a
pw_labeled    a
output        0
Name: 38, dtype: object
sl_labeled    a
sw_labeled    b
pl_labeled    a
pw_labeled    a
output        0
Name: 38, dtype: object
sl_labeled    b
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 39, dtype: object
sl_labeled    b
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 39, dtype: object
sl_labeled    b
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 39, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 40, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 40, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 40, dtype: object
sl_labeled    a
sw_labeled    a
pl_labeled    a
pw_labeled    a
output        0
Name: 41, dtype: object
sl_labeled    a
sw_labeled    a
pl_labeled    a
pw_labeled    a
output        0
Name: 41, dtype: object
sl_labeled    a
sw_labeled    a
pl_labeled    a
pw_labeled    a
output        0
Name: 41, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 42, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 42, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 42, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 43, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 43, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 43, dtype: object
sl_labeled    b
sw_labeled    d
pl_labeled    a
pw_labeled    a
output        0
Name: 44, dtype: object
sl_labeled    b
sw_labeled    d
pl_labeled    a
pw_labeled    a
output        0
Name: 44, dtype: object
sl_labeled    b
sw_labeled    d
pl_labeled    a
pw_labeled    a
output        0
Name: 44, dtype: object
sl_labeled    a
sw_labeled    b
pl_labeled    a
pw_labeled    a
output        0
Name: 45, dtype: object
sl_labeled    a
sw_labeled    b
pl_labeled    a
pw_labeled    a
output        0
Name: 45, dtype: object
sl_labeled    a
sw_labeled    b
pl_labeled    a
pw_labeled    a
output        0
Name: 45, dtype: object
sl_labeled    b
sw_labeled    d
pl_labeled    a
pw_labeled    a
output        0
Name: 46, dtype: object
sl_labeled    b
sw_labeled    d
pl_labeled    a
pw_labeled    a
output        0
Name: 46, dtype: object
sl_labeled    b
sw_labeled    d
pl_labeled    a
pw_labeled    a
output        0
Name: 46, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 47, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 47, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 47, dtype: object
sl_labeled    b
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 48, dtype: object
sl_labeled    b
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 48, dtype: object
sl_labeled    b
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 48, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 49, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 49, dtype: object
sl_labeled    a
sw_labeled    c
pl_labeled    a
pw_labeled    a
output        0
Name: 49, dtype: object
sl_labeled    d
sw_labeled    c
pl_labeled    c
pw_labeled    c
output        1
Name: 50, dtype: object
sl_labeled    d
sw_labeled    c
pl_labeled    c
pw_labeled    c
output        1
Name: 50, dtype: object
sl_labeled    d
sw_labeled    c
pl_labeled    c
pw_labeled    c
output        1
Name: 50, dtype: object
sl_labeled    c
sw_labeled    c
pl_labeled    c
pw_labeled    c
output        1
Name: 51, dtype: object
sl_labeled    c
sw_labeled    c
pl_labeled    c
pw_labeled    c
output        1
Name: 51, dtype: object
sl_labeled    c
sw_labeled    c
pl_labeled    c
pw_labeled    c
output        1
Name: 51, dtype: object
sl_labeled    d
sw_labeled    c
pl_labeled    c
pw_labeled    c
output        1
Name: 52, dtype: object
sl_labeled    d
sw_labeled    c
pl_labeled    c
pw_labeled    c
output        1
Name: 52, dtype: object
sl_labeled    d
sw_labeled    c
pl_labeled    c
pw_labeled    c
output        1
Name: 52, dtype: object
sl_labeled    b
sw_labeled    a
pl_labeled    c
pw_labeled    c
output        1
Name: 53, dtype: object
sl_labeled    b
sw_labeled    a
pl_labeled    c
pw_labeled    c
output        1
Name: 53, dtype: object
sl_labeled    b
sw_labeled    a
pl_labeled    c
pw_labeled    c
output        1
Name: 53, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    c
pw_labeled    c
output        1
Name: 54, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    c
pw_labeled    c
output        1
Name: 54, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    c
pw_labeled    c
output        1
Name: 54, dtype: object
sl_labeled    b
sw_labeled    b
pl_labeled    c
pw_labeled    c
output        1
Name: 55, dtype: object
sl_labeled    b
sw_labeled    b
pl_labeled    c
pw_labeled    c
output        1
Name: 55, dtype: object
sl_labeled    b
sw_labeled    b
pl_labeled    c
pw_labeled    c
output        1
Name: 55, dtype: object
sl_labeled    c
sw_labeled    c
pl_labeled    c
pw_labeled    c
output        1
Name: 56, dtype: object
sl_labeled    c
sw_labeled    c
pl_labeled    c
pw_labeled    c
output        1
Name: 56, dtype: object
sl_labeled    c
sw_labeled    c
pl_labeled    c
pw_labeled    c
output        1
Name: 56, dtype: object
sl_labeled    a
sw_labeled    a
pl_labeled    b
pw_labeled    b
output        1
Name: 57, dtype: object
sl_labeled    a
sw_labeled    a
pl_labeled    b
pw_labeled    b
output        1
Name: 57, dtype: object
sl_labeled    a
sw_labeled    a
pl_labeled    b
pw_labeled    b
output        1
Name: 57, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    c
pw_labeled    c
output        1
Name: 58, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    c
pw_labeled    c
output        1
Name: 58, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    c
pw_labeled    c
output        1
Name: 58, dtype: object
sl_labeled    b
sw_labeled    b
pl_labeled    c
pw_labeled    c
output        1
Name: 59, dtype: object
sl_labeled    b
sw_labeled    b
pl_labeled    c
pw_labeled    c
output        1
Name: 59, dtype: object
sl_labeled    b
sw_labeled    b
pl_labeled    c
pw_labeled    c
output        1
Name: 59, dtype: object
sl_labeled    a
sw_labeled    a
pl_labeled    b
pw_labeled    b
output        1
Name: 60, dtype: object
sl_labeled    a
sw_labeled    a
pl_labeled    b
pw_labeled    b
output        1
Name: 60, dtype: object
sl_labeled    a
sw_labeled    a
pl_labeled    b
pw_labeled    b
output        1
Name: 60, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    c
pw_labeled    c
output        1
Name: 61, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    c
pw_labeled    c
output        1
Name: 61, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    c
pw_labeled    c
output        1
Name: 61, dtype: object
sl_labeled    c
sw_labeled    a
pl_labeled    c
pw_labeled    b
output        1
Name: 62, dtype: object
sl_labeled    c
sw_labeled    a
pl_labeled    c
pw_labeled    b
output        1
Name: 62, dtype: object
sl_labeled    c
sw_labeled    a
pl_labeled    c
pw_labeled    b
output        1
Name: 62, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    c
pw_labeled    c
output        1
Name: 63, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    c
pw_labeled    c
output        1
Name: 63, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    c
pw_labeled    c
output        1
Name: 63, dtype: object
sl_labeled    b
sw_labeled    b
pl_labeled    b

Name: 103, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    d
pw_labeled    c
output        2
Name: 103, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    d
pw_labeled    c
output        2
Name: 103, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    d
pw_labeled    d
output        2
Name: 104, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    d
pw_labeled    d
output        2
Name: 104, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    d
pw_labeled    d
output        2
Name: 104, dtype: object
sl_labeled    d
sw_labeled    b
pl_labeled    d
pw_labeled    d
output        2
Name: 105, dtype: object
sl_labeled    d
sw_labeled    b
pl_labeled    d
pw_labeled    d
output        2
Name: 105, dtype: object
sl_labeled    d
sw_labeled    b
pl_labeled    d
pw_labeled    d
output        2
Name: 105, dtype: object
sl_labeled    a
sw_labeled    a
pl_labeled    c
pw_labeled    c
output        2
Name: 106, dtype: object
sl_labeled    a
sw_labeled    a
pl_labeled    c
pw_labeled    c
output        2
Name: 106, dtype: object
sl_labeled    a
sw_labeled    a
pl_labeled    c
pw_labeled    c
output        2
Name: 106, dtype: object
sl_labeled    d
sw_labeled    b
pl_labeled    d
pw_labeled    c
output        2
Name: 107, dtype: object
sl_labeled    d
sw_labeled    b
pl_labeled    d
pw_labeled    c
output        2
Name: 107, dtype: object
sl_labeled    d
sw_labeled    b
pl_labeled    d
pw_labeled    c
output        2
Name: 107, dtype: object
sl_labeled    c
sw_labeled    a
pl_labeled    d
pw_labeled    c
output        2
Name: 108, dtype: object
sl_labeled    c
sw_labeled    a
pl_labeled    d
pw_labeled    c
output        2
Name: 108, dtype: object
sl_labeled    c
sw_labeled    a
pl_labeled    d
pw_labeled    c
output        2
Name: 108, dtype: object
sl_labeled    d
sw_labeled    c
pl_labeled    d
pw_labeled    d
output        2
Name: 109, dtype: object
sl_labeled    d
sw_labeled    c
pl_labeled    d
pw_labeled    d
output        2
Name: 109, dtype: object
sl_labeled    d
sw_labeled    c
pl_labeled    d
pw_labeled    d
output        2
Name: 109, dtype: object
sl_labeled    c
sw_labeled    c
pl_labeled    c
pw_labeled    d
output        2
Name: 110, dtype: object
sl_labeled    c
sw_labeled    c
pl_labeled    c
pw_labeled    d
output        2
Name: 110, dtype: object
sl_labeled    c
sw_labeled    c
pl_labeled    c
pw_labeled    d
output        2
Name: 110, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    c
pw_labeled    d
output        2
Name: 111, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    c
pw_labeled    d
output        2
Name: 111, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    c
pw_labeled    d
output        2
Name: 111, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    d
pw_labeled    d
output        2
Name: 112, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    d
pw_labeled    d
output        2
Name: 112, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    d
pw_labeled    d
output        2
Name: 112, dtype: object
sl_labeled    b
sw_labeled    a
pl_labeled    c
pw_labeled    d
output        2
Name: 113, dtype: object
sl_labeled    b
sw_labeled    a
pl_labeled    c
pw_labeled    d
output        2
Name: 113, dtype: object
sl_labeled    b
sw_labeled    a
pl_labeled    c
pw_labeled    d
output        2
Name: 113, dtype: object
sl_labeled    b
sw_labeled    b
pl_labeled    c
pw_labeled    d
output        2
Name: 114, dtype: object
sl_labeled    b
sw_labeled    b
pl_labeled    c
pw_labeled    d
output        2
Name: 114, dtype: object
sl_labeled    b
sw_labeled    b
pl_labeled    c
pw_labeled    d
output        2
Name: 114, dtype: object
sl_labeled    c
sw_labeled    c
pl_labeled    c
pw_labeled    d
output        2
Name: 115, dtype: object
sl_labeled    c
sw_labeled    c
pl_labeled    c
pw_labeled    d
output        2
Name: 115, dtype: object
sl_labeled    c
sw_labeled    c
pl_labeled    c
pw_labeled    d
output        2
Name: 115, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    d
pw_labeled    c
output        2
Name: 116, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    d
pw_labeled    c
output        2
Name: 116, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    d
pw_labeled    c
output        2
Name: 116, dtype: object
sl_labeled    d
sw_labeled    d
pl_labeled    d
pw_labeled    d
output        2
Name: 117, dtype: object
sl_labeled    d
sw_labeled    d
pl_labeled    d
pw_labeled    d
output        2
Name: 117, dtype: object
sl_labeled    d
sw_labeled    d
pl_labeled    d
pw_labeled    d
output        2
Name: 117, dtype: object
sl_labeled    d
sw_labeled    b
pl_labeled    d
pw_labeled    d
output        2
Name: 118, dtype: object
sl_labeled    d
sw_labeled    b
pl_labeled    d
pw_labeled    d
output        2
Name: 118, dtype: object
sl_labeled    d
sw_labeled    b
pl_labeled    d
pw_labeled    d
output        2
Name: 118, dtype: object
sl_labeled    c
sw_labeled    a
pl_labeled    c
pw_labeled    c
output        2
Name: 119, dtype: object
sl_labeled    c
sw_labeled    a
pl_labeled    c
pw_labeled    c
output        2
Name: 119, dtype: object
sl_labeled    c
sw_labeled    a
pl_labeled    c
pw_labeled    c
output        2
Name: 119, dtype: object
sl_labeled    d
sw_labeled    c
pl_labeled    d
pw_labeled    d
output        2
Name: 120, dtype: object
sl_labeled    d
sw_labeled    c
pl_labeled    d
pw_labeled    d
output        2
Name: 120, dtype: object
sl_labeled    d
sw_labeled    c
pl_labeled    d
pw_labeled    d
output        2
Name: 120, dtype: object
sl_labeled    b
sw_labeled    b
pl_labeled    c
pw_labeled    d
output        2
Name: 121, dtype: object
sl_labeled    b
sw_labeled    b
pl_labeled    c
pw_labeled    d
output        2
Name: 121, dtype: object
sl_labeled    b
sw_labeled    b
pl_labeled    c
pw_labeled    d
output        2
Name: 121, dtype: object
sl_labeled    d
sw_labeled    b
pl_labeled    d
pw_labeled    d
output        2
Name: 122, dtype: object
sl_labeled    d
sw_labeled    b
pl_labeled    d
pw_labeled    d
output        2
Name: 122, dtype: object
sl_labeled    d
sw_labeled    b
pl_labeled    d
pw_labeled    d
output        2
Name: 122, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    c
pw_labeled    c
output        2
Name: 123, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    c
pw_labeled    c
output        2
Name: 123, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    c
pw_labeled    c
output        2
Name: 123, dtype: object
sl_labeled    c
sw_labeled    c
pl_labeled    d
pw_labeled    d
output        2
Name: 124, dtype: object
sl_labeled    c
sw_labeled    c
pl_labeled    d
pw_labeled    d
output        2
Name: 124, dtype: object
sl_labeled    c
sw_labeled    c
pl_labeled    d
pw_labeled    d
output        2
Name: 124, dtype: object
sl_labeled    d
sw_labeled    c
pl_labeled    d
pw_labeled    c
output        2
Name: 125, dtype: object
sl_labeled    d
sw_labeled    c
pl_labeled    d
pw_labeled    c
output        2
Name: 125, dtype: object
sl_labeled    d
sw_labeled    c
pl_labeled    d
pw_labeled    c
output        2
Name: 125, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    c
pw_labeled    c
output        2
Name: 126, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    c
pw_labeled    c
output        2
Name: 126, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    c
pw_labeled    c
output        2
Name: 126, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    c
pw_labeled    c
output        2
Name: 127, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    c
pw_labeled    c
output        2
Name: 127, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    c
pw_labeled    c
output        2
Name: 127, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    d
pw_labeled    d
output        2
Name: 128, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    d
pw_labeled    d
output        2
Name: 128, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    d
pw_labeled    d
output        2
Name: 128, dtype: object
sl_labeled    d
sw_labeled    b
pl_labeled    d
pw_labeled    c
output        2
Name: 129, dtype: object
sl_labeled    d
sw_labeled    b
pl_labeled    d
pw_labeled    c
output        2
Name: 129, dtype: object
sl_labeled    d
sw_labeled    b
pl_labeled    d
pw_labeled    c
output        2
Name: 129, dtype: object
sl_labeled    d
sw_labeled    b
pl_labeled    d
pw_labeled    d
output        2
Name: 130, dtype: object
sl_labeled    d
sw_labeled    b
pl_labeled    d
pw_labeled    d
output        2
Name: 130, dtype: object
sl_labeled    d
sw_labeled    b
pl_labeled    d
pw_labeled    d
output        2
Name: 130, dtype: object
sl_labeled    d
sw_labeled    d
pl_labeled    d
pw_labeled    d
output        2
Name: 131, dtype: object
sl_labeled    d
sw_labeled    d
pl_labeled    d
pw_labeled    d
output        2
Name: 131, dtype: object
sl_labeled    d
sw_labeled    d
pl_labeled    d
pw_labeled    d
output        2
Name: 131, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    d
pw_labeled    d
output        2
Name: 132, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    d
pw_labeled    d
output        2
Name: 132, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    d
pw_labeled    d
output        2
Name: 132, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    c
pw_labeled    c
output        2
Name: 133, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    c
pw_labeled    c
output        2
Name: 133, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    c
pw_labeled    c
output        2
Name: 133, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    d
pw_labeled    c
output        2
Name: 134, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    d
pw_labeled    c
output        2
Name: 134, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    d
pw_labeled    c
output        2
Name: 134, dtype: object
sl_labeled    d
sw_labeled    b
pl_labeled    d
pw_labeled    d
output        2
Name: 135, dtype: object
sl_labeled    d
sw_labeled    b
pl_labeled    d
pw_labeled    d
output        2
Name: 135, dtype: object
sl_labeled    d
sw_labeled    b
pl_labeled    d
pw_labeled    d
output        2
Name: 135, dtype: object
sl_labeled    c
sw_labeled    c
pl_labeled    d
pw_labeled    d
output        2
Name: 136, dtype: object
sl_labeled    c
sw_labeled    c
pl_labeled    d
pw_labeled    d
output        2
Name: 136, dtype: object
sl_labeled    c
sw_labeled    c
pl_labeled    d
pw_labeled    d
output        2
Name: 136, dtype: object
sl_labeled    c
sw_labeled    c
pl_labeled    d
pw_labeled    c
output        2
Name: 137, dtype: object
sl_labeled    c
sw_labeled    c
pl_labeled    d
pw_labeled    c
output        2
Name: 137, dtype: object
sl_labeled    c
sw_labeled    c
pl_labeled    d
pw_labeled    c
output        2
Name: 137, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    c
pw_labeled    c
output        2
Name: 138, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    c
pw_labeled    c
output        2
Name: 138, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    c
pw_labeled    c
output        2
Name: 138, dtype: object
sl_labeled    d
sw_labeled    c
pl_labeled    d
pw_labeled    d
output        2
Name: 139, dtype: object
sl_labeled    d
sw_labeled    c
pl_labeled    d
pw_labeled    d
output        2
Name: 139, dtype: object
sl_labeled    d
sw_labeled    c
pl_labeled    d
pw_labeled    d
output        2
Name: 139, dtype: object
sl_labeled    c
sw_labeled    c
pl_labeled    d
pw_labeled    d
output        2
Name: 140, dtype: object
sl_labeled    c
sw_labeled    c
pl_labeled    d
pw_labeled    d
output        2
Name: 140, dtype: object
sl_labeled    c
sw_labeled    c
pl_labeled    d
pw_labeled    d
output        2
Name: 140, dtype: object
sl_labeled    d
sw_labeled    c
pl_labeled    c
pw_labeled    d
output        2
Name: 141, dtype: object
sl_labeled    d
sw_labeled    c
pl_labeled    c
pw_labeled    d
output        2
Name: 141, dtype: object
sl_labeled    d
sw_labeled    c
pl_labeled    c
pw_labeled    d
output        2
Name: 141, dtype: object
sl_labeled    b
sw_labeled    b
pl_labeled    c
pw_labeled    d
output        2
Name: 142, dtype: object
sl_labeled    b
sw_labeled    b
pl_labeled    c
pw_labeled    d
output        2
Name: 142, dtype: object
sl_labeled    b
sw_labeled    b
pl_labeled    c
pw_labeled    d
output        2
Name: 142, dtype: object
sl_labeled    c
sw_labeled    c
pl_labeled    d
pw_labeled    d
output        2
Name: 143, dtype: object
sl_labeled    c
sw_labeled    c
pl_labeled    d
pw_labeled    d
output        2
Name: 143, dtype: object
sl_labeled    c
sw_labeled    c
pl_labeled    d
pw_labeled    d
output        2
Name: 143, dtype: object
sl_labeled    c
sw_labeled    c
pl_labeled    d
pw_labeled    d
output        2
Name: 144, dtype: object
sl_labeled    c
sw_labeled    c
pl_labeled    d
pw_labeled    d
output        2
Name: 144, dtype: object
sl_labeled    c
sw_labeled    c
pl_labeled    d
pw_labeled    d
output        2
Name: 144, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    c
pw_labeled    d
output        2
Name: 145, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    c
pw_labeled    d
output        2
Name: 145, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    c
pw_labeled    d
output        2
Name: 145, dtype: object
sl_labeled    c
sw_labeled    a
pl_labeled    c
pw_labeled    d
output        2
Name: 146, dtype: object
sl_labeled    c
sw_labeled    a
pl_labeled    c
pw_labeled    d
output        2
Name: 146, dtype: object
sl_labeled    c
sw_labeled    a
pl_labeled    c
pw_labeled    d
output        2
Name: 146, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    c
pw_labeled    d
output        2
Name: 147, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    c
pw_labeled    d
output        2
Name: 147, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    c
pw_labeled    d
output        2
Name: 147, dtype: object
sl_labeled    c
sw_labeled    c
pl_labeled    d
pw_labeled    d
output        2
Name: 148, dtype: object
sl_labeled    c
sw_labeled    c
pl_labeled    d
pw_labeled    d
output        2
Name: 148, dtype: object
sl_labeled    c
sw_labeled    c
pl_labeled    d
pw_labeled    d
output        2
Name: 148, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    c
pw_labeled    c
output        2
Name: 149, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    c
pw_labeled    c
output        2
Name: 149, dtype: object
sl_labeled    c
sw_labeled    b
pl_labeled    c
pw_labeled    c
output        2
Name: 149, dtype: object

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

In [100]:
def predict(x, counts):
    y = list()
    for index, row in x.iterrows():
        y.append(pred_row(row, counts))
    return y

In [103]:
def pred_row(row, counts):
    for i in counts:
        pred_for_class(pi[i], row, counts[i])

In [107]:
def pred_for_class(p_y, row, c):
    pro = 1
    keys = list(c.keys())
    tot = keys[0]
    for i in range(len(x)):
        pro *= c[keys[i]][]